/**
 * playtest1r [OWNER-APPROVED 2026-10-04 09:00 ET: playtest1r fully reshaped big bosses]: each big sheet's
 * silhouette as the game needs it, measured by tools/sprite-writer/boss_writer.py from the sheets it draws (do not
 * edit by hand; re-run the writer): top = how high the body stands over its feet point (stand, idle, walk; front and
 * side), half = how far it reaches either side in any pose, body = its half-width at mid-height (the hurt radius),
 * foot = the ground it covers (front width, side depth). All in px at the sheet's scale. bigboss.ts reads it.
 */
export type BigShape = { top: number; half: number; body: number; foot: { rx: number; ry: number } };
export const BIG_SHAPES: Record<string, BigShape> = {
  "bat-boss": { top: 153, half: 56, body: 20, foot: { rx: 14, ry: 6 } },
  "bat-mini": { top: 93, half: 34, body: 10, foot: { rx: 7, ry: 3 } },
  "bat-rare": { top: 63, half: 22, body: 5, foot: { rx: 3, ry: 2 } },
  "cat-boss": { top: 112, half: 47, body: 20, foot: { rx: 18, ry: 8 } },
  "cat-mini": { top: 68, half: 28, body: 10, foot: { rx: 9, ry: 4 } },
  "cat-rare": { top: 46, half: 20, body: 5, foot: { rx: 4, ry: 2 } },
  "ghost-boss": { top: 148, half: 41, body: 22, foot: { rx: 14, ry: 6 } },
  "ghost-mini": { top: 83, half: 25, body: 11, foot: { rx: 7, ry: 3 } },
  "ghost-rare": { top: 56, half: 17, body: 5, foot: { rx: 3, ry: 2 } },
  "ghoul-boss": { top: 101, half: 56, body: 28, foot: { rx: 14, ry: 6 } },
  "ghoul-mini": { top: 61, half: 34, body: 14, foot: { rx: 7, ry: 3 } },
  "ghoul-rare": { top: 42, half: 22, body: 6, foot: { rx: 3, ry: 2 } },
  "goblin-boss": { top: 118, half: 55, body: 16, foot: { rx: 15, ry: 7 } },
  "goblin-mini": { top: 67, half: 33, body: 8, foot: { rx: 8, ry: 4 } },
  "goblin-rare": { top: 45, half: 22, body: 4, foot: { rx: 3, ry: 2 } },
  "horse-boss": { top: 116, half: 50, body: 17, foot: { rx: 16, ry: 7 } },
  "horse-mini": { top: 71, half: 32, body: 8, foot: { rx: 8, ry: 4 } },
  "horse-rare": { top: 47, half: 22, body: 4, foot: { rx: 4, ry: 2 } },
  "krampus-boss": { top: 136, half: 57, body: 19, foot: { rx: 15, ry: 7 } },
  "lantern-boss": { top: 142, half: 57, body: 22, foot: { rx: 14, ry: 6 } },
  "lantern-mini": { top: 86, half: 34, body: 11, foot: { rx: 7, ry: 3 } },
  "lantern-rare": { top: 58, half: 23, body: 5, foot: { rx: 3, ry: 2 } },
  "lich-boss": { top: 138, half: 56, body: 25, foot: { rx: 24, ry: 11 } },
  "lich-mini": { top: 83, half: 34, body: 13, foot: { rx: 12, ry: 5 } },
  "lich-rare": { top: 56, half: 23, body: 6, foot: { rx: 5, ry: 2 } },
  "mimic-rare": { top: 34, half: 15, body: 8, foot: { rx: 5, ry: 2 } },
  "mummy-boss": { top: 132, half: 56, body: 24, foot: { rx: 14, ry: 6 } },
  "mummy-mini": { top: 79, half: 33, body: 12, foot: { rx: 7, ry: 3 } },
  "mummy-rare": { top: 54, half: 22, body: 5, foot: { rx: 3, ry: 2 } },
  "pumpkin-lord-boss": { top: 143, half: 56, body: 27, foot: { rx: 24, ry: 11 } },
  "rat-boss": { top: 85, half: 55, body: 16, foot: { rx: 17, ry: 8 } },
  "rat-mini": { top: 50, half: 33, body: 8, foot: { rx: 8, ry: 4 } },
  "rat-rare": { top: 34, half: 22, body: 4, foot: { rx: 4, ry: 2 } },
  "scarecrow-boss": { top: 129, half: 55, body: 16, foot: { rx: 14, ry: 6 } },
  "scarecrow-mini": { top: 78, half: 33, body: 8, foot: { rx: 7, ry: 3 } },
  "scarecrow-rare": { top: 53, half: 22, body: 4, foot: { rx: 3, ry: 2 } },
  "skeleton-boss": { top: 130, half: 55, body: 23, foot: { rx: 14, ry: 6 } },
  "skeleton-mini": { top: 77, half: 32, body: 12, foot: { rx: 7, ry: 3 } },
  "skeleton-rare": { top: 52, half: 21, body: 5, foot: { rx: 3, ry: 2 } },
  "tree-boss": { top: 138, half: 57, body: 16, foot: { rx: 24, ry: 11 } },
  "tree-mini": { top: 79, half: 35, body: 8, foot: { rx: 12, ry: 5 } },
  "tree-rare": { top: 53, half: 23, body: 4, foot: { rx: 5, ry: 2 } },
  "vampire-boss": { top: 139, half: 56, body: 24, foot: { rx: 24, ry: 11 } },
  "vampire-mini": { top: 82, half: 34, body: 12, foot: { rx: 12, ry: 5 } },
  "vampire-rare": { top: 54, half: 22, body: 5, foot: { rx: 5, ry: 2 } },
  "witch-boss": { top: 159, half: 56, body: 20, foot: { rx: 24, ry: 11 } },
  "witch-mini": { top: 93, half: 33, body: 10, foot: { rx: 12, ry: 5 } },
  "witch-rare": { top: 62, half: 22, body: 5, foot: { rx: 5, ry: 2 } },
  "wolf-boss": { top: 125, half: 56, body: 31, foot: { rx: 14, ry: 6 } },
  "wolf-mini": { top: 75, half: 34, body: 16, foot: { rx: 7, ry: 3 } },
  "wolf-rare": { top: 51, half: 23, body: 7, foot: { rx: 3, ry: 2 } },
  "zombie-boss": { top: 137, half: 56, body: 16, foot: { rx: 16, ry: 7 } },
  "zombie-mini": { top: 83, half: 34, body: 8, foot: { rx: 8, ry: 4 } },
  "zombie-rare": { top: 56, half: 22, body: 4, foot: { rx: 4, ry: 2 } },
};
